version: '3.8'

services:
  postgres:
    container_name: bd_gestao_api_courses_postgres
    image: postgres
    ports:
      - 5430:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_api_courses